variables:
  BASENAME: go-ethereum

stages:
  - check
  - build
  - mirror

check:
  image: yrzr/docker-arm32v7:stable-git
  stage: check
  tags:
    - armhf
    - docker
  only:
    - branches
  script:
    - apk add --no-cache openssh-client bash curl coreutils
    - git config --global user.email $GIT_USER_EMAIL && git config --global user.name $GIT_USER_NAME
    - mkdir -p ~/.ssh && echo "$GITLAB_SSH_PRIV_KEY" > ~/.ssh/id_rsa && ssh-keyscan -H git.yrzr.ocry.com > ~/.ssh/known_hosts && chmod -R 0600 ~/.ssh/
    - git fetch --tags && ./check-version.sh && ./create-tags.sh
    - git push --tags https://${GITLAB_USER_LOGIN}:${PERSONAL_ACCESS_TOKEN}@git.yrzr.ocry.com/docker/go-ethereum-arm.git

.build_stage: &build_stage
  image: yrzr/docker-arm32v7:stable-dind-git
  stage: build
  only:
    - tags
  before_script:
    # setup dockerd
    - /usr/local/bin/dockerd-entrypoint.sh &
    - apk add --no-cache bash coreutils git
    - docker info || sleep 5 && docker info
    # fetch source code
    - wget "https://github.com/ethereum/go-ethereum/archive/${CI_COMMIT_TAG}.tar.gz" -O go-ethereum.tar.gz
    - tar -xpvf go-ethereum.tar.gz 
  script:
    - cd go-ethereum*
    # build
    - sed -i "s/golang\:.*as/${BASE_IMAGE_GOLANG} as/" ./Dockerfile*
    - sed -i "s/alpine\:.*/${BASE_IMAGE_ALPINE}/" ./Dockerfile*
    - docker build -t ${DOCKER_NS}/${BASENAME}-${ARMVER}:${CI_COMMIT_TAG} -f ./Dockerfile ./
    - docker build -t ${DOCKER_NS}/${BASENAME}-${ARMVER}:alltools-${CI_COMMIT_TAG} -f ./Dockerfile.alltools ./
    # little DAG version for mining at low end devices on private network
    - sed -i 's/datasetInitBytes   = 1 << 30/datasetInitBytes   = 1 << 20/' consensus/ethash/algorithm.go
    - sed -i 's/datasetGrowthBytes = 1 << 23/datasetGrowthBytes = 1 << 13/' consensus/ethash/algorithm.go
    - docker build -t ${DOCKER_NS}/${BASENAME}-${ARMVER}-little-dag:${CI_COMMIT_TAG} -f ./Dockerfile ./
    - docker build -t ${DOCKER_NS}/${BASENAME}-${ARMVER}-little-dag:alltools-${CI_COMMIT_TAG} -f ./Dockerfile.alltools ./
    # latest tag
    - cd ../ && git fetch --tags && ./latest-tag.sh
    # docker push
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD 
    - docker images && docker push ${DOCKER_NS}/${BASENAME}-${ARMVER} && docker push ${DOCKER_NS}/${BASENAME}-${ARMVER}-little-dag

build-armv7:
  <<: *build_stage
  image: yrzr/docker-arm32v7:stable-dind
  tags:
    - armhf
    - docker
  variables:
    ARMVER: arm32v7
    BASE_IMAGE_GOLANG: yrzr\/golang-arm32v7:alpine
    BASE_IMAGE_ALPINE: arm32v6\/alpine:latest

build-armv8:
  <<: *build_stage
  image: arm64v8/docker:stable-dind
  tags:
    - aarch64
    - docker
  variables:
    ARMVER: arm64v8
    BASE_IMAGE_GOLANG: arm64v8\/golang:alpine
    BASE_IMAGE_ALPINE: arm64v8\/alpine:latest

mirror:
  image: yrzr/docker-arm32v7:stable-git
  stage: mirror
  tags:
    - armhf
  only:
    - master
  except:
    - schedules
  script:
    - mkdir -p ~/.ssh
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - ssh-keyscan -H github.com > ~/.ssh/known_hosts
    - chmod -R 0600 ~/.ssh/
    - git remote | grep github || git remote add github git@github.com:yrzr/go-ethereum-arm.git
    - git fetch github
    - git push github "$CI_BUILD_REF_NAME" -f
